folio-org/ui-plugin-find-finc-metadata-collection

- translations/ui-plugin-find-finc-metadata-collection/ar.json
- translations/ui-plugin-find-finc-metadata-collection/ca.json
- translations/ui-plugin-find-finc-metadata-collection/da.json
- translations/ui-plugin-find-finc-metadata-collection/de.json
- translations/ui-plugin-find-finc-metadata-collection/en_GB.json
- translations/ui-plugin-find-finc-metadata-collection/en_SE.json
- translations/ui-plugin-find-finc-metadata-collection/en_US.json
- translations/ui-plugin-find-finc-metadata-collection/es.json
- translations/ui-plugin-find-finc-metadata-collection/es_419.json
- translations/ui-plugin-find-finc-metadata-collection/es_ES.json
- translations/ui-plugin-find-finc-metadata-collection/fr.json
- translations/ui-plugin-find-finc-metadata-collection/fr_FR.json
- translations/ui-plugin-find-finc-metadata-collection/he.json
- translations/ui-plugin-find-finc-metadata-collection/hu.json
- translations/ui-plugin-find-finc-metadata-collection/it_IT.json
- translations/ui-plugin-find-finc-metadata-collection/ja.json
- translations/ui-plugin-find-finc-metadata-collection/pt_BR.json
- translations/ui-plugin-find-finc-metadata-collection/pt_PT.json
- translations/ui-plugin-find-finc-metadata-collection/ru.json
- translations/ui-plugin-find-finc-metadata-collection/ur.json
- translations/ui-plugin-find-finc-metadata-collection/zh_CN.json
- translations/ui-plugin-find-finc-metadata-collection/zh_TW.json
> Update translation strings as of 20200319T202257

- translations/ui-plugin-find-finc-metadata-collection/zh_CN.json
> Update translation strings as of 20200413T183215

- translations/ui-plugin-find-finc-metadata-collection/ar.json
- translations/ui-plugin-find-finc-metadata-collection/ca.json
- translations/ui-plugin-find-finc-metadata-collection/da.json
- translations/ui-plugin-find-finc-metadata-collection/de.json
- translations/ui-plugin-find-finc-metadata-collection/en_GB.json
- translations/ui-plugin-find-finc-metadata-collection/en_SE.json
- translations/ui-plugin-find-finc-metadata-collection/en_US.json
- translations/ui-plugin-find-finc-metadata-collection/es.json
- translations/ui-plugin-find-finc-metadata-collection/es_419.json
- translations/ui-plugin-find-finc-metadata-collection/es_ES.json
- translations/ui-plugin-find-finc-metadata-collection/fr.json
- translations/ui-plugin-find-finc-metadata-collection/fr_FR.json
- translations/ui-plugin-find-finc-metadata-collection/he.json
- translations/ui-plugin-find-finc-metadata-collection/hu.json
- translations/ui-plugin-find-finc-metadata-collection/it_IT.json
- translations/ui-plugin-find-finc-metadata-collection/ja.json
- translations/ui-plugin-find-finc-metadata-collection/pt_BR.json
- translations/ui-plugin-find-finc-metadata-collection/pt_PT.json
- translations/ui-plugin-find-finc-metadata-collection/ru.json
- translations/ui-plugin-find-finc-metadata-collection/ur.json
- translations/ui-plugin-find-finc-metadata-collection/zh_CN.json
- translations/ui-plugin-find-finc-metadata-collection/zh_TW.json
> Update translation strings as of 20200423T142657

- translations/ui-plugin-find-finc-metadata-collection/ar.json
- translations/ui-plugin-find-finc-metadata-collection/pt_BR.json
- translations/ui-plugin-find-finc-metadata-collection/ru.json
> Update translation strings as of 20200424T193712

- translations/ui-plugin-find-finc-metadata-collection/fr_FR.json
- translations/ui-plugin-find-finc-metadata-collection/ru.json
> Update translation strings as of 20200428T150732

- translations/ui-plugin-find-finc-metadata-collection/fr_FR.json
- translations/ui-plugin-find-finc-metadata-collection/zh_CN.json
> Update translation strings as of 20200505T210535

- translations/ui-plugin-find-finc-metadata-collection/fr_FR.json
> Update translation strings as of 20200519T123842

- translations/ui-plugin-find-finc-metadata-collection/ru.json
> Update translation strings as of 20200626T180122

- package.json
- src/CollectionFilters.js
- src/CollectionSearchContainer.js
- src/CollectionSearchModal.js
- src/CollectionsView.js
- src/filterConfigData.js
Richard, it seems to be working. What do you think?
> Uifc 153 add assigned unassigned filter

- translations/ui-plugin-find-finc-metadata-collection/ar.json
- translations/ui-plugin-find-finc-metadata-collection/ca.json
- translations/ui-plugin-find-finc-metadata-collection/da.json
- translations/ui-plugin-find-finc-metadata-collection/de.json
- translations/ui-plugin-find-finc-metadata-collection/en_GB.json
- translations/ui-plugin-find-finc-metadata-collection/en_SE.json
- translations/ui-plugin-find-finc-metadata-collection/en_US.json
- translations/ui-plugin-find-finc-metadata-collection/es.json
- translations/ui-plugin-find-finc-metadata-collection/es_419.json
- translations/ui-plugin-find-finc-metadata-collection/es_ES.json
- translations/ui-plugin-find-finc-metadata-collection/fr.json
- translations/ui-plugin-find-finc-metadata-collection/fr_FR.json
- translations/ui-plugin-find-finc-metadata-collection/he.json
- translations/ui-plugin-find-finc-metadata-collection/hu.json
- translations/ui-plugin-find-finc-metadata-collection/it_IT.json
- translations/ui-plugin-find-finc-metadata-collection/ja.json
- translations/ui-plugin-find-finc-metadata-collection/pt_BR.json
- translations/ui-plugin-find-finc-metadata-collection/pt_PT.json
- translations/ui-plugin-find-finc-metadata-collection/ru.json
- translations/ui-plugin-find-finc-metadata-collection/ur.json
- translations/ui-plugin-find-finc-metadata-collection/zh_CN.json
- translations/ui-plugin-find-finc-metadata-collection/zh_TW.json
> Update translation strings as of 20200804T150835

- translations/ui-plugin-find-finc-metadata-collection/pt_BR.json
> Update translation strings as of 20200806T130626

- translations/ui-plugin-find-finc-metadata-collection/it_IT.json
> Update translation strings as of 20200813T135432

- translations/ui-plugin-find-finc-metadata-collection/it_IT.json
- translations/ui-plugin-find-finc-metadata-collection/zh_CN.json
> Update translation strings as of 20200827T215834

- translations/ui-plugin-find-finc-metadata-collection/ar.json
- translations/ui-plugin-find-finc-metadata-collection/ca.json
- translations/ui-plugin-find-finc-metadata-collection/da.json
- translations/ui-plugin-find-finc-metadata-collection/de.json
- translations/ui-plugin-find-finc-metadata-collection/en_GB.json
- translations/ui-plugin-find-finc-metadata-collection/en_SE.json
- translations/ui-plugin-find-finc-metadata-collection/en_US.json
- translations/ui-plugin-find-finc-metadata-collection/es.json
- translations/ui-plugin-find-finc-metadata-collection/es_419.json
- translations/ui-plugin-find-finc-metadata-collection/es_ES.json
- translations/ui-plugin-find-finc-metadata-collection/fr.json
- translations/ui-plugin-find-finc-metadata-collection/fr_FR.json
- translations/ui-plugin-find-finc-metadata-collection/he.json
- translations/ui-plugin-find-finc-metadata-collection/hu.json
- translations/ui-plugin-find-finc-metadata-collection/it_IT.json
- translations/ui-plugin-find-finc-metadata-collection/ja.json
- translations/ui-plugin-find-finc-metadata-collection/pt_BR.json
- translations/ui-plugin-find-finc-metadata-collection/pt_PT.json
- translations/ui-plugin-find-finc-metadata-collection/ru.json
- translations/ui-plugin-find-finc-metadata-collection/ur.json
- translations/ui-plugin-find-finc-metadata-collection/zh_CN.json
- translations/ui-plugin-find-finc-metadata-collection/zh_TW.json
> Update translation strings as of 20200910T134908

- translations/ui-plugin-find-finc-metadata-collection/hi_IN.json
- translations/ui-plugin-find-finc-metadata-collection/ko.json
> Update translation strings as of 20200921T192032

- translations/ui-plugin-find-finc-metadata-collection/fr_FR.json
- translations/ui-plugin-find-finc-metadata-collection/zh_CN.json
> Update translation strings as of 20200928T202231

- translations/ui-plugin-find-finc-metadata-collection/ar.json
- translations/ui-plugin-find-finc-metadata-collection/ca.json
- translations/ui-plugin-find-finc-metadata-collection/da.json
- translations/ui-plugin-find-finc-metadata-collection/de.json
- translations/ui-plugin-find-finc-metadata-collection/en_GB.json
- translations/ui-plugin-find-finc-metadata-collection/en_SE.json
- translations/ui-plugin-find-finc-metadata-collection/en_US.json
- translations/ui-plugin-find-finc-metadata-collection/es.json
- translations/ui-plugin-find-finc-metadata-collection/es_419.json
- translations/ui-plugin-find-finc-metadata-collection/es_ES.json
- translations/ui-plugin-find-finc-metadata-collection/fr.json
- translations/ui-plugin-find-finc-metadata-collection/fr_FR.json
- translations/ui-plugin-find-finc-metadata-collection/he.json
- translations/ui-plugin-find-finc-metadata-collection/hi_IN.json
- translations/ui-plugin-find-finc-metadata-collection/hu.json
- translations/ui-plugin-find-finc-metadata-collection/it_IT.json
- translations/ui-plugin-find-finc-metadata-collection/ja.json
- translations/ui-plugin-find-finc-metadata-collection/ko.json
- translations/ui-plugin-find-finc-metadata-collection/pl.json
- translations/ui-plugin-find-finc-metadata-collection/pt_BR.json
- translations/ui-plugin-find-finc-metadata-collection/pt_PT.json
- translations/ui-plugin-find-finc-metadata-collection/ru.json
- translations/ui-plugin-find-finc-metadata-collection/ur.json
- translations/ui-plugin-find-finc-metadata-collection/zh_CN.json
- translations/ui-plugin-find-finc-metadata-collection/zh_TW.json
> Update translation strings as of 20201007T133333

- translations/ui-plugin-find-finc-metadata-collection/pt_BR.json
> Update translation strings as of 20201008T220807

- translations/ui-plugin-find-finc-metadata-collection/es.json
- translations/ui-plugin-find-finc-metadata-collection/es_419.json
- translations/ui-plugin-find-finc-metadata-collection/es_ES.json
> Update translation strings as of 20201016T144229

- translations/ui-plugin-find-finc-metadata-collection/ja.json
> Update translation strings as of 20201102T140138

- translations/ui-plugin-find-finc-metadata-collection/it_IT.json
- translations/ui-plugin-find-finc-metadata-collection/ja.json
> Update translation strings as of 20201105T151643

- translations/ui-plugin-find-finc-metadata-collection/ber.json
> Update translation strings as of 20201109T135508

- Jenkinsfile
- package.json
https://issues.folio.org/browse/UIFC-249
> UIFC-249: Translation-ast

- .eslintrc
- package.json
- src/CollectionsView.js
- test/bigtest/.eslintrc.js
- test/bigtest/tests/find-collection-test.js
https://issues.folio.org/browse/UIFC-271
> UIFC-271 replace babel eslint

- src/CollectionSearchContainer.js
- src/filterConfigData.js
- test/bigtest/tests/find-collection-test.js
https://issues.folio.org/browse/UIFC-285
> UIFC-285: fix filter

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIFC-292
> UIFC-292: bump stripes to 8.0.0 for Orchid

- CHANGELOG.md
- src/CollectionFilters.js
- src/CollectionFilters.test.js
- src/CollectionSearch.js
- src/CollectionSearch.test.js
- src/CollectionSearchContainer.js
- src/CollectionSearchContainer.test.js
- src/CollectionSearchModal.js
- src/CollectionSearchModal.test.js
- src/CollectionView.test.js
- src/CollectionsView.js
- test/jest/helpers/renderWithIntl.js
https://folio-org.atlassian.net/browse/UIFC-362
> UIFC-362 use functional components

- CHANGELOG.md
- src/CollectionView.test.js
- src/CollectionsView.js
https://folio-org.atlassian.net/browse/UIFC-358
> UIFC-358: Update results if deleting search string via keyboard

- CHANGELOG.md
- package.json
https://folio-org.atlassian.net/browse/UIFC-386
See https://github.com/folio-org/mod-finc-config/pull/152
> [UIFC-386] Update required interfaces
